# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruby-nagios}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["R.I.Pienaar"]
  s.date = %q{2010-07-11}
  s.default_executable = %q{nagsrv.rb}
  s.description = %q{
Have you ever had to disable alerts, retry a check or acknowledge outages on a large amount of services with Nagios and hated the web UI for it?

This is a CLI tool and Ruby library that parses your status log file and let you query it for information or create external commands to be piped into the nagios command file. 
}
  s.email = %q{rip@devco.net}
  s.executables = ["nagsrv.rb"]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "COPYING",
     "README",
     "Rakefile",
     "bin/nagsrv.rb",
     "lib/nagios/status.rb",
     "lib/ruby-nagios.rb"
  ]
  s.homepage = %q{http://code.google.com/p/ruby-nagios/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{CLI and Ruby library for querying nagios services status}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

